local _, ns = ...

ns.RegisterEnum("FRAME_STRATA", {
    WORLD = " WORLD",
    BACKGROUND = "BACKGROUND",
    LOW = " LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH",
    DIALOG = "DIALOG",
    FULLSCREEN = "FULLSCREEN",
    FULLSCREEN_DIALOG = " FULLSCREEN_DIALOG",
    TOOLTIP = " TOOLTIP",
})

ns.RegisterEnum("durabilityType", {
    Bars = "BAR",
    Text = "TEXT",
})

ns.RegisterEnum("slotIdType", {
    INVSLOT_HEAD = INVSLOT_HEAD,
    INVSLOT_NECK = INVSLOT_NECK,
    INVSLOT_SHOULDER = INVSLOT_SHOULDER,
    INVSLOT_CHEST = INVSLOT_CHEST,
    INVSLOT_WAIST = INVSLOT_WAIST,
    INVSLOT_LEGS = INVSLOT_LEGS,
    INVSLOT_FEET = INVSLOT_FEET,
    INVSLOT_WRIST = INVSLOT_WRIST,
    INVSLOT_HAND = INVSLOT_HAND,
    INVSLOT_FINGER1 = INVSLOT_FINGER1,
    INVSLOT_FINGER2 = INVSLOT_FINGER2,
    INVSLOT_TRINKET1 = INVSLOT_TRINKET1,
    INVSLOT_TRINKET2 = INVSLOT_TRINKET2,
    INVSLOT_BACK = INVSLOT_BACK,
    INVSLOT_MAINHAND = INVSLOT_MAINHAND,
    INVSLOT_OFFHAND = INVSLOT_OFFHAND,
    INVSLOT_RANGED = INVSLOT_RANGED,
    INVSLOT_TABARD = INVSLOT_TABARD,
    INVSLOT_AMMO = INVSLOT_AMMO,
})

ns.RegisterEnum("slotNameType", {
    INVSLOT_HEAD = "HeadSlot",
    INVSLOT_NECK = "NeckSlot",
    INVSLOT_SHOULDER = "ShoulderSlot",
    INVSLOT_CHEST = "ChestSlot",
    INVSLOT_WAIST = "WaistSlot",
    INVSLOT_LEGS = "LegsSlot",
    INVSLOT_FEET = "FeetSlot",
    INVSLOT_WRIST = "WristSlot",
    INVSLOT_HAND = "HandsSlot",
    INVSLOT_FINGER1 = "Finger0Slot",
    INVSLOT_FINGER2 = "Finger1Slot",
    INVSLOT_TRINKET1 = "Trinket0Slot",
    INVSLOT_TRINKET2 = "Trinket1Slot",
    INVSLOT_BACK = "BackSlot",
    INVSLOT_MAINHAND = "MainHandSlot",
    INVSLOT_OFFHAND = "SecondaryHandSlot",
    INVSLOT_RANGED = "RangedSlot",
    INVSLOT_TABARD = "TabardSlot",
    INVSLOT_AMMO = "AmmoSlot",
})
